In [45]:
import pandas as pd
import numpy as np

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [46]:
iris = datasets.load_iris()

In [47]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x : iris.target_names[x] )
df[47 : 52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size= 0.3)

In [49]:
model = svm.SVC(kernel= 'rbf', C= 30, gamma= 'auto')
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

0.9111111111111111

In [50]:
cross_val_score(svm.SVC(kernel= 'linear', C= 10, gamma= 'auto'), iris.data, iris.target, cv= 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [51]:
cross_val_score(svm.SVC(kernel= 'rbf', C= 10, gamma= 'auto'), iris.data, iris.target, cv= 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [52]:
cross_val_score(svm.SVC(kernel= 'rbf', C= 20, gamma= 'auto'), iris.data, iris.target, cv= 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [53]:
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_scores = {}

for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel= kval, C= cval, gamma= 'auto'), iris.data, iris.target, cv= 5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
        
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}